<?xml version="1.0" ?>
<testsuite errors="2" failures="0" name="Test_Class-20210401111358" tests="11" time="0.159">
	<testcase classname="Test_Class" name="test_Commom_Utils" time="0.002"/>
	<testcase classname="Test_Class" name="test_Google_Babynames" time="0.002"/>
	<testcase classname="Test_Class" name="test_Google_Exercise_1" time="0.002"/>
	<testcase classname="Test_Class" name="test_Google_Exercise_2" time="0.002"/>
	<testcase classname="Test_Class" name="test_Google_Exercise_3" time="0.026"/>
	<testcase classname="Test_Class" name="test_Google_Exercise_4" time="0.016"/>
	<testcase classname="Test_Class" name="test_Google_Exercise_5" time="0.034"/>
	<testcase classname="Test_Class" name="test_Google_Exercise_6" time="0.019"/>
	<testcase classname="Test_Class" name="test_Python_Pytest" time="0.022"/>
	<testcase classname="Test_Class" name="test_Python_OOP" time="0.033">
		<error message="" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "Test_Wrapper.py", line 66, in test_Python_OOP
    assert sum == 10
AssertionError
]]>		</error>
	</testcase>
	<testcase classname="Test_Class" name="test_to_fail" time="0.000">
		<error message="'Test_Class' object does not support indexing" type="TypeError">
<![CDATA[Traceback (most recent call last):
  File "Test_Wrapper.py", line 60, in test_to_fail
    assert tuple_data[4]['size'] == 1023 #Fail
TypeError: 'Test_Class' object does not support indexing
]]>		</error>
	</testcase>
	<system-out>
<![CDATA[...............Common Utils Test Completed................
...............Google Test Completed................
...............Pytest Test Completed................
]]>	</system-out>
	<system-err>
<![CDATA[]]>	</system-err>
</testsuite>
